version: 2

sources:
  # Source definition for the staging layer
  - name: flights_staging
    database: demo
    schema: bookings
    tables:
      - name: flights
        columns:
          - name: flight_id
          - name: flight_no
          - name: scheduled_departure
          - name: scheduled_arrival
          - name: departure_airport
          - name: arrival_airport
          - name: status
          - name: aircraft_code
          - name: actual_departure
          - name: actual_arrival
      - name: airports_data
        columns:
          - name: airport_code
          - name: airport_name
          - name: city
          - name: coordinates
          - name: timezone
      - name: ticket_flights
        columns:
          - name: ticket_no
          - name: flight_id
          - name: fare_conditions
          - name: amount

models:
  # Model definitions for the Kimball Integration Layer
  - name: dim_airports
    description: "A dimension table containing information about airports in the Kimball model."
    columns:
      - name: airport_sk
      - name: airport_code
      - name: airport_name
      - name: city
      - name: coordinates
      - name: timezone

  - name: fct_flights
    description: "A fact table containing metrics and keys for flights in the Kimball model."
    columns:
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: scheduled_arrival
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: departure_airport_sk
      - name: arrival_airport_sk

  - name: new_fct_flights
    description: "A new fact table at the ticket grain, combining flight and ticket data."
    columns:
      - name: ticket_id
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: scheduled_arrival
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: departure_airport_sk
      - name: arrival_airport_sk
      - name: fare_conditions
      - name: amount 

  - name: fct_tickets
    description: "A fact table containing metrics and keys for tickets in the Kimball model."
    columns:
      - name: ticket_no
      - name: flight_id
      - name: fare_conditions
      - name: amount

  - name: rollback_fct_flights
    description: "A rollback version of the original fact table containing metrics and keys for flights in the Kimball model."
    columns:
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: scheduled_arrival
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: departure_airport_sk
      - name: arrival_airport_sk

  # Model definitions for the Kimball Presentation Layer
  - name: kimball_mart_flight_information
    description: "A Kimball star schema mart combining flight and airport data for easy querying."
    columns:
      - name: flight_id
      - name: flight_no
      - name: departure_airport_code
      - name: departure_airport_name
      - name: departure_city
      - name: arrival_airport_code
      - name: arrival_airport_name
      - name: arrival_city
      - name: scheduled_duration_minutes

  - name: new_kimball_mart_flight_information
    description: "A new Kimball star schema mart at the ticket grain, combining flight, ticket, and airport data for easy querying."
    columns:
      - name: flight_id
      - name: flight_no
      - name: departure_airport_code
      - name: departure_airport_name
      - name: departure_city
      - name: arrival_airport_code
      - name: arrival_airport_name
      - name: arrival_city
      - name: scheduled_duration_minutes

  - name: kimball_revenue_by_flight_v1
    description: "A Kimball star schema mart providing revenue information by flight Option 1 (rebuild data model)"
    columns:
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: departure_city
      - name: arrival_city
      - name: status
      - name: ticket_sold
      - name: total_revenue
      - name: avg_ticket_price
      - name: economy_tickets
      - name: business_tickets
      - name: economy_revenue
      - name: business_revenue
  
  - name: kimball_revenue_by_flight_v2
    description: "A Kimball star schema mart providing revenue information by flight Option 2 (multiple fact tables)"
    columns:
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: departure_city
      - name: arrival_city
      - name: status
      - name: ticket_sold
      - name: total_revenue
      - name: avg_ticket_price
      - name: economy_tickets
      - name: business_tickets
      - name: economy_revenue
      - name: business_revenue

  # Model definitions for the Data Vault Raw Layer
  - name: hub_airport
    description: "A Hub table storing unique airport business keys in the Data Vault model."
    columns:
      - name: airport_pk
      - name: airport_code
      - name: load_dts
      - name: record_source

  - name: sat_airport
    description: "A Satellite table containing descriptive attributes for airports in the Data Vault model."
    columns:
      - name: airport_pk
      - name: airport_name
      - name: city
      - name: coordinates
      - name: timezone
      - name: load_dts
      - name: record_source

  - name: hub_flights
    description: "A Hub table storing unique airport business keys in the Data Vault model."
    columns:
      - name: airport_pk
      - name: airport_code
      - name: load_dts
      - name: record_source

  - name: sat_flights
    description: "A Satellite table containing descriptive attributes for flights in the Data Vault model."
    columns:
      - name: flight_pk
      - name: flight_id
      - name: flight_no
      - name: schedule_departure
      - name: schedule_arrival
      - name: departure_airport
      - name: arrival_airport
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: load_dts
      - name: record_source

  - name: link_flights_airport
    description: "A Link table defining the relationship between flights and airports in the Data Vault model."
    columns:
      - name: flight_pk
      - name: departure_airport_pk
      - name: arrival_airport_pk
      - name: load_dts
      - name: record_source

  - name: hub_tickets
    description: "A Hub table storing unique ticket business keys in the Data Vault model."
    columns:
      - name: ticket_pk
      - name: ticket_no
      - name: load_dts
      - name: record_source
  
  - name: sat_tickets
    description: "A Satellite table containing descriptive attributes for tickets in the Data Vault model."
    columns:
      - name: ticket_pk
      - name: fare_conditions
      - name: amount
      - name: load_dts
      - name: record_source
  
  - name: link_ticket_flights
    description: "A Link table defining the relationship between tickets and flights in the Data Vault model."
    columns:
      - name: ticket_flights_pk
      - name: ticket_pk
      - name: flights_pk
      - name: load_dts
      - name: record_source

  # Model definitions for the Data Vault Presentation Layer
  - name: dv_mart_flight_information
    description: "A Data Vault mart combining flight and airport data for easy querying."
    columns:
      - name: flight_id
      - name: flight_no
      - name: departure_airport_code
      - name: departure_airport_name
      - name: departure_city
      - name: arrival_airport_code
      - name: arrival_airport_name
      - name: arrival_city
      - name: scheduled_duration_minutes

  - name: dv_mart_revenue_by_flight
    description: "A Data Vault mart providing revenue information by flight."
    columns:
      - name: flight_id
      - name: flight_no
      - name: scheduled_departure
      - name: departure_city
      - name: arrival_city
      - name: status
      - name: ticket_sold
      - name: total_revenue
      - name: avg_ticket_price
      - name: economy_tickets
      - name: business_tickets
      - name: economy_revenue
      - name: business_revenue
      