version: 2

sources:
  - name: flights_staging
    database: demo
    schema: bookings
    tables:
      - name: flights
        columns:
          - name: flight_id
          - name: flight_no
          - name: scheduled_departure
          - name: scheduled_arrival
          - name: departure_airport
          - name: arrival_airport
          - name: status
          - name: aircraft_code
          - name: actual_departure
          - name: actual_arrival
      - name: airports_data
        columns:
          - name: airport_code
          - name: airport_name
          - name: city
          - name: coordinates
          - name: timezone
      - name: ticket_flights
        columns:
          - name: ticket_no
          - name: flight_id
          - name: fare_conditions
          - name: amount

models:
  - name: dim_airports
    description: "A dimension table containing information about airports in the Kimball model."
    columns:
      - name: airport_sk
        tests:
          - unique
          - not_null
      - name: airport_code
        tests:
          - not_null
      - name: airport_name
        tests:
          - unique
      - name: city
        tests:
          - not_null
      - name: coordinates
        tests:
          - not_null
      - name: timezone
        tests:
          - not_null

  - name: fct_flights
    description: "A fact table containing metrics and keys for flights in the Kimball model."
    columns:
      - name: flight_id
        tests:
          - unique
          - not_null
      - name: flight_no
        tests:
          - not_null
      - name: scheduled_departure
        tests:
          - not_null
      - name: scheduled_arrival
        tests:
          - not_null
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: departure_airport_sk
      - name: arrival_airport_sk

  - name: new_fct_flights
    description: "A new fact table at the ticket grain, combining flight and ticket data."
    columns:
      - name: ticket_id
        tests:
          - unique
          - not_null
      - name: flight_id
        tests:
          - not_null
      - name: flight_no
        tests:
          - not_null
      - name: scheduled_departure
        tests:
          - not_null
      - name: scheduled_arrival
        tests:
          - not_null
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: departure_airport_sk
      - name: arrival_airport_sk
      - name: fare_conditions
      - name: amount 

  - name: fct_tickets
    description: "A fact table containing metrics and keys for tickets in the Kimball model."
    columns:
      - name: ticket_no
        tests:
          - unique
          - not_null
      - name: flight_id
        tests:
          - not_null
      - name: fare_conditions
      - name: amount

  - name: hub_airport
    description: "A Hub table storing unique airport business keys in the Data Vault model."
    columns:
      - name: airport_pk
        tests:
          - unique
          - not_null
      - name: airport_code
        tests:
          - unique
          - not_null
      - name: load_dts
      - name: record_source

  - name: sat_airport
    description: "A Satellite table containing descriptive attributes for airports in the Data Vault model."
    columns:
      - name: airport_pk
        tests:
          - unique
          - not_null
      - name: airport_name
        tests:
          - not_null
      - name: city
        tests:
          - not_null
      - name: coordinates
        tests:
          - not_null
      - name: timezone
        tests:
          - not_null
      - name: load_dts
      - name: record_source

  - name: hub_flights
    description: "A Hub table storing unique airport business keys in the Data Vault model."
    columns:
      - name: airport_pk
        tests:
          - unique
          - not_null
      - name: airport_code
        tests:
          - unique
          - not_null
      - name: load_dts
      - name: record_source

  - name: sat_flights
    description: "A Satellite table containing descriptive attributes for flights in the Data Vault model."
    columns:
      - name: flight_pk
        tests:
          - unique
          - not_null
      - name: flight_id
        tests:
          - unique
          - not_null
      - name: flight_no
        tests:
          - not_null
      - name: schedule_departure
        tests:
          - not_null
      - name: schedule_arrival
        tests:
          - not_null
      - name: departure_airport
        tests:
          - not_null
      - name: arrival_airport
        tests:
          - not_null
      - name: status
      - name: aircraft_code
      - name: actual_departure
      - name: actual_arrival
      - name: load_dts
      - name: record_source

  - name: link_flights_airport
    description: "A Link table defining the relationship between flights and airports in the Data Vault model."
    columns:
      - name: flight_pk
        tests:
          - unique
          - not_null
      - name: departure_airport_pk
        tests:
          - not_null
      - name: arrival_airport_pk
        tests:
          - not_null
      - name: load_dts
      - name: record_source

  - name: hub_tickets
    description: "A Hub table storing unique ticket business keys in the Data Vault model."
    columns:
      - name: ticket_pk
        tests:
          - unique
          - not_null
      - name: ticket_no
        tests:
          - unique
          - not_null
      - name: load_dts
      - name: record_source
  
  - name: sat_tickets
    description: "A Satellite table containing descriptive attributes for tickets in the Data Vault model."
    columns:
      - name: ticket_pk
        tests:
          - unique
          - not_null
      - name: fare_conditions
      - name: amount
      - name: load_dts
      - name: record_source
  
  - name: link_ticket_flights
    description: "A Link table defining the relationship between tickets and flights in the Data Vault model."
    columns:
      - name: ticket_flights_pk
        tests:
          - unique
          - not_null
      - name: ticket_pk
        tests:
          - not_null
      - name: flights_pk
        tests:
          - not_null
      - name: load_dts
      - name: record_source
